### ISSUE TITLE
Create usage documentation

### ISSUE THREAD

**Issue by cattz** [valenssoftware/bamboo-templatedplans-plugin#1]
It's not easy to understand how to use the plugin based on the [Atlassian page](https://marketplace.atlassian.com/plugins/org.valens.bamboo-templatedplans-plugin)

The `README.md` file in this repo points to this page.

The bare minimum would be to explain how to copy the template over an existing plan!

(Thanks for creating this plugin)

**Comment by giulio1979** [comment]
Wrote few lines in the Readme.
