### ISSUE TITLE
Deployment Plans still need manual task update after replication to be enabled

### ISSUE THREAD

**Issue by addteq-roberto** [valenssoftware/bamboo-templatedplans-plugin#10]
After creating an empty plan, normally one has to add an extra task so it can be deployed (else Bamboo shows an alert saying "Plan needs another task"). Replication from a template should take care of this, but it doesn't, even though tasks are properly replicated the error is still there and prevents deployment. To workaround it i have to create a new empty task, save it, and remove it, so Bamboo thinks a new task has been added.

**Comment by giulio1979** [comment]
Hi,

I will check it next week, I was always having a checkout task or artifact downloading before the template tasks probably that is why I have never encountered the issue.

Julius

**Comment by addteq-roberto** [comment]
No problem, i saw that just a couple of days ago you added deployment plan support, so no rush

**Comment by giulio1979** [comment]
Commited and released fix.
