### ISSUE TITLE
PluginModuleKey property gets lost when copying requirements

### ISSUE THREAD

**Issue by Vertigo093i** [valenssoftware/bamboo-templatedplans-plugin#3]
When creating a copy of a `Requirement` the plugin doesn't copy its `PluginModuleKey` property which leads to incorrect and duplicate requirements for jobs.

**Comment by giulio1979** [comment]
You mean we should try with: newRequirement.setPluginModuleKey(requirement.getPluginModuleKey()); ?

**Comment by giulio1979** [comment]
added the statement above and released

**Comment by Vertigo093i** [comment]
I think so. Or may be the better way is to use the other constructor which
accepts an original requirement. This will help to avoid similar problems
if another property would be added in the future.

**Comment by giulio1979** [comment]
Good idea, will change implementation to use copy constructor.

**Comment by Vertigo093i** [comment]
Tested the new version and it works as expected.

Thank you for such a great plugin!
