### ISSUE TITLE
"Propagate changes" from the template, not the child

### ISSUE THREAD

**Issue by paladinlogic** [valenssoftware/bamboo-templatedplans-plugin#4]
It seems a bit odd to trigger propagating a job template's changes on the saving of the Miscellaneous tab of a child of the job template. A user is already in the job template when working on those changes, having a "propagate" button there would be logical.

**Comment by giulio1979** [comment]
this should be the case actually.

**Comment by giulio1979** [comment]
Only if you save templates you will trigger replication, otherwise from experience bamboo will start replications very often in a large organisation ( my case 200 plans with 6 templates :) ). 

boolean state = true;

                    BuildDefinition buildDefinition = p.getBuildDefinition();

                    if (buildDefinition.getCustomConfiguration().get(SELECTED_TEMPLATE_ENABLED) == null
                            || buildDefinition.getCustomConfiguration().get(SELECTED_TEMPLATE_ENABLED).equalsIgnoreCase("false")) {
                        state = false;
                    }

                    if (state) {
                        serverLifecycleManager.pauseServer();
                        int k = 0;
                        while (serverLifecycleManager.getServerLifecycleState().equals(ServerLifecycleState.PAUSING) && k++ < 300) {
                            try {
                                Thread.sleep(1000);
                            } catch (InterruptedException ex) {
                                log.error(ex.getMessage(), ex);
                            }

                        }

                        synchronized (sync) {
                            try {
                                doReplication();
                            } catch (Exception e) {
                                log.warn("Received BuildConfigurationUpdatedEvent error ", e);
                            }
                        }

                        serverLifecycleManager.resumeServer();
                    }
