### ISSUE TITLE
Template List not showing

### ISSUE THREAD

**Issue by FlxPeters** [valenssoftware/bamboo-templatedplans-plugin#5]
Bamboo version 5.9.7 build 5920 
Plugin Version 2.0
Bamboo Trail Licence

Hi,

i marked a plan as template, but when i'm on another plan i don' t see the template list. Just the checkbox. But it is not marked. 

Is this a known bug. Maybe with the Bamboo Version or trail licence?
I use the embedded DB.

**Comment by giulio1979** [comment]
I am on 5.9.7 build 5920 - 14 Oct 15

[image: Inline image 1]

[image: Inline image 2]

Also Trial license ... no issues.

I dont know what to say, unless you get some exception in the logs nothing
should be impacting you you have similar stuff like me.

The plugin is free, doesn't have any license restrictions or hidden stuff
that would block functionality.

If you like maybe you can send me a chunk of catalina.out log, do a save on
template and a refresh on the child plan.

Julius

**Comment by FlxPeters** [comment]
Hm, ok. I had a look to catalina.out. Nothing special there. 

Do i need a special connection between the plans, something like project etc. to get the list?

**Comment by giulio1979** [comment]
Nope, nothing there either.

Try to set DEBUG for package org.valens in your logging settings, see if
this gives you more info in logs.

Julius

**Comment by FlxPeters** [comment]
sry, my fault. I was on the other plans tab, not in the job...

**Comment by giulio1979** [comment]
Happens :)

Best wishes,
Julius
