### ISSUE TITLE
Propagate changes appears to change which template a job belongs to

### ISSUE THREAD

**Issue by glianeric** [valenssoftware/bamboo-templatedplans-plugin#6]
I have a small number of templates (some of which may be clones of another)

- The specific problem I have is this: I have set up a plan that uses my 'update snapshots' template (A) for several jobs within the same plan (1)
- I have set up a plan that uses a release template (B) for several jobs with the same plan (2)

  What happens is that at some point, my plan (1) ends up having its jobs referencing template (B). This may be happening during replication (ie. when I click the 'save' button on the template's plan's misc tab), but I'm not certain.

  It looks like a somewhat bad bug. Can you help? I'm on bamboo 5.9.3, using version 2.0 of the plugin.

  I can run a number of limited experiments to try and track the problem down, and I can read from the DB as well if necessary.

**Comment by giulio1979** [comment]
Hi,

first of all we should try to see in the log the replication.

log.warn("Found a plan ( " + job.getKey() + " ) that has a template " + selectedKey);

Can you search for lines stating which plan is based on which plan according to configuration.

**Comment by glianeric** [comment]
I have for example:
( GENERICS-JAVAGENERICS-JAVACACHE ) that has a template PT-JAVACOMPONENTSNAPSHOTJGITREL-JRS

( GENERICS-JUPDATESNAPSHOTS-JAVACACHE ) that has a template PT-CBNGENUPDATE-JOB1

This is correct, but what seems to happen at times is (and I just grepped to actually find this in my logs):

( GENERICS-JUPDATESNAPSHOTS-JAVACACHE ) that has a template PT-JAVACOMPONENTSNAPSHOTJGITREL-JRS

**Comment by giulio1979** [comment]
Hmmm, I dont see how it would be possible. Can you look in the log if there was maybe another configuration change done around there, maybe someone else updating the templates ? My environment runs currently 6 template plans and 240 templated build plans with automatic branches but I have no issues at all. The only difference I see, I don't have circular referencing.

Any chance you can extract the main job template into a separate plan and base the other on it ?

**Comment by glianeric** [comment]
Can you explain circular referencing?   I don't have a template pointing to another template as far as I can tell.

**Comment by giulio1979** [comment]
Sorry I got confused by the statement "for several jobs within the same plan" but now that I see the keys is clear they are different.

To tell the truth I don't see any reason for your scenario. Can you try to read the logs a bit around the area and see if there is anything suspicious like multiple BuildConfiguration events ? 

I can try tomorrow to see if I can block some operations in the plugin just to avoid any concurrency issues.

**Comment by glianeric** [comment]
I don't see anything that looks particularly suspicious to me right now, but I will keep an eye on this,
I'll try running another replication and see if it affects the particular jobs that have been misbehaving.
Is there anything I should look for in the database, by the way?

**Comment by glianeric** [comment]
Oh, and, is there any debugging I can turn on for your plugin?

**Comment by giulio1979** [comment]
Try to go under logging in Bamboo and put the org.valens as package name with level DEBUG

**Comment by glianeric** [comment]
It's turned on now.   I have made some changes and propagated them - so far, so good ... I guess we'll see how things hold up.
I'll leave the debugging on and monitor.   If I run across this again I'll provide as much information here as possible.

**Comment by giulio1979** [comment]
Thanks, lets see. The process is quite heavy, while I tried to keep methods from overlapping and avoid concurrency issues I would advise to propagate changes with caution, when there are few builds running.
