### ISSUE TITLE
Templating Deployment jobs

### ISSUE THREAD

**Issue by akumria** [valenssoftware/bamboo-templatedplans-plugin#8]
Hi,

I quite like the look of this plugin -- but this only seems to apply to build-time jobs.

I have a need for templated deployment jobs (e.g. a template, and then multiple environments with the tasks kept in sync).

Do you know if such a plugin exists? Am I thinking about this problem the wrong way?

Any advice / insight appreciated.

**Comment by giulio1979** [comment]
Hi,

As far as I know there are zero extension points in bamboo where I could
hook something like that. I never saw anyone managing to do something like
that unfortunately.

If I hear anything about this topic I can keep you in the loop.

Best regards,
J
